type Bank = {
  label: string;
  value: string;
  image: string;
  limitACN?: number;
  minLimitACN?: number;
  maxLimitACN?: number;
};

export const banks: Bank[] = [
  {
    image: "/bank/ABL-Logo-Allied-Bank-Limited.jpg",
    label: "Allied Bank",
    value: "Allied-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Askari-Bank.png",
    label: "Askari Bank",
    value: "Askari-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/alfalah.png",
    label: "Alfalah Bank",
    value: "Alfalah-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },

  {
    image: "/bank/bank-Al-Habib.png",
    label: "Bank-Al Habib",
    value: "Bank-Al-Habib",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Bankislami.png",
    label: "Bank Islami",
    value: "Bank-Islami",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Bank-of-Punjab.jpg",
    label: "Bank Of Punjab",
    value: "Bank-of-punjab",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Burj-Bank.jpg",
    label: "Bank Burj",
    value: "Burj-bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/faysal-bank.png",
    label: "Faysal Bank",
    value: "Faysal-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/HBL_logo.png",
    label: "Habib Bank (HBL)",
    value: "Habib-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Js-Bank.jpg",
    label: "JS Bank",
    value: "JS-Bank",
    minLimitACN: 6,
    maxLimitACN: 25,
  },
  {
    image: "/bank/kasb-bank.jpg",
    label: "KASB Bank",
    value: "Kasb-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/NIB-Bank.png",
    label: "NIB Bank",
    value: "Nib-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Standard_Chartered_bank.png",
    label: "Standard Chartered Bank",
    value: "standard-chartered-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/silkBank.png",
    label: "Silk Bank",
    value: "Silk-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Soneri-Bank.jpeg",
    label: "Soneri Bank",
    value: "Soneri-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/summit-bank.png",
    label: "Summit Bank",
    value: "Summit-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Tameer-Bank.png",
    label: "Tameer MircroFinance Bank",
    value: "Tameer-MircoFinance-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/UBL.png",
    label: "United Bank Limited (UBL)",
    value: "United-Bank-Limited",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/dubai-islamic-bank.jpg",
    label: "Dubai Islamic",
    value: "Dubai-Islamic",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/meezan_bank.jpg",
    label: "Meezan Bank",
    value: "Meezan-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/APNA-BANK.jpg",
    label: "APNA Microfinance Bank",
    value: "Microfinance-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/samba-bank.jpg",
    label: "SAMBA Bank",
    value: "Samba-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/sindh-bank.jpg",
    label: "Sindh Bank",
    value: "Sindh-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Al-Baraka-bank.png",
    label: "Al-Barka Bank",
    value: "Al-barka-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Habib-Metropolitan-Bank.jpg",
    label: "Habib Metropolitan Bank (HMB)",
    value: "Habib-Metropolitan-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/First-Women-Bank.png",
    label: "First Women Bank",
    value: "First-Women-Bank",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/Industrial_and_Commercial_Bank_of_China_logo.png",
    label: "Bank Industrial and Commercial Bank of China",
    value: "Bank-Industrial-and-Commercial-Bank-of-China",
    minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/MCB-Bank.jpg",
    label: "MCB Bank",
    value: "MCB-Bank",
   minLimitACN: 9,
    maxLimitACN: 25,
  },
  {
    image: "/bank/U-Bank.jpg",
    label: "U Microfinance Bank Limited",
    value: "U-Microfinance-Bank-Limited",
    minLimitACN: 9,
    maxLimitACN: 25,
    
  },
  // {
  //   image: "/bank/easypaisa.png",
  //   label: "Easypasa",
  //   value: "Easypasa",
  //   limitACN: 11,
  // },
  // {
  //   image: "/bank/jazz-cash.jpg",
  //   label: "Jazz Cash",
  //   value: "Jazz-Cash",
  //   limitACN: 11,
  // },
];
